# Generated by Django 4.2.7 on 2026-06-23 16:01

import bookings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_resource_image_url_resource_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image of your resource (max 5MB)', null=True, upload_to='resources/', validators=[bookings.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='resource',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional: Link to an image URL', null=True),
        ),
    ]
