# Generated by Django 4.2.7 on 2026-06-24 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_remove_payment_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=50, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Amenities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MeetingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(blank=True, max_length=20, null=True)),
                ('floor_number', models.IntegerField(default=1)),
                ('building_name', models.CharField(blank=True, max_length=100, null=True)),
                ('seating_capacity', models.IntegerField(default=0, help_text='Seating capacity')),
                ('standing_capacity', models.IntegerField(default=0, help_text='Standing capacity')),
                ('classroom_capacity', models.IntegerField(default=0, help_text='Classroom setup capacity')),
                ('theater_capacity', models.IntegerField(default=0, help_text='Theater setup capacity')),
                ('has_projector', models.BooleanField(default=False)),
                ('has_whiteboard', models.BooleanField(default=False)),
                ('has_video_conferencing', models.BooleanField(default=False)),
                ('has_phone', models.BooleanField(default=False)),
                ('has_smart_tv', models.BooleanField(default=False)),
                ('has_audio_system', models.BooleanField(default=False)),
                ('has_wifi', models.BooleanField(default=True)),
                ('has_air_conditioning', models.BooleanField(default=True)),
                ('is_accessible', models.BooleanField(default=True, help_text='Wheelchair accessible')),
                ('room_size_sqft', models.IntegerField(blank=True, help_text='Room size in square feet', null=True)),
                ('natural_light', models.BooleanField(default=False)),
                ('has_window', models.BooleanField(default=True)),
                ('default_setup_time', models.IntegerField(default=15, help_text='Default setup time in minutes')),
                ('default_teardown_time', models.IntegerField(default=15, help_text='Default teardown time in minutes')),
                ('floor_plan', models.ImageField(blank=True, null=True, upload_to='floor_plans/')),
                ('room_photo', models.ImageField(blank=True, null=True, upload_to='room_photos/')),
                ('notes', models.TextField(blank=True, help_text='Any additional notes about the room')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenities', models.ManyToManyField(blank=True, related_name='meeting_rooms', to='bookings.amenity')),
                ('resource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_room', to='bookings.resource')),
            ],
        ),
    ]
