# Generated by Django 4.2.7 on 2026-06-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_amenity_meetingroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='floor_plan',
            field=models.ImageField(blank=True, help_text='Upload a floor plan of the room', null=True, upload_to='floor_plans/'),
        ),
        migrations.AddField(
            model_name='resource',
            name='room_photo',
            field=models.ImageField(blank=True, help_text='Upload a photo of the room', null=True, upload_to='room_photos/'),
        ),
    ]
