# Generated by Django 4.2.7 on 2026-06-24 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0011_resource_floor_plan_resource_room_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '⭐ 1 - Poor'), (2, '⭐⭐ 2 - Fair'), (3, '⭐⭐⭐ 3 - Good'), (4, '⭐⭐⭐⭐ 4 - Very Good'), (5, '⭐⭐⭐⭐⭐ 5 - Excellent')])),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('comment', models.TextField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('is_verified', models.BooleanField(default=False, help_text='Verified purchase - user actually booked this resource')),
                ('helpful_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(blank=True, help_text='The booking this review is for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='bookings.booking')),
                ('helpful_users', models.ManyToManyField(blank=True, related_name='helpful_reviews', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='bookings.resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['resource', 'rating'], name='bookings_re_resourc_d8f35d_idx'), models.Index(fields=['user', 'created_at'], name='bookings_re_user_id_991413_idx'), models.Index(fields=['status'], name='bookings_re_status_77942b_idx')],
                'unique_together': {('user', 'resource')},
            },
        ),
    ]
