# Generated by Django 4.2.7 on 2026-06-24 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0012_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='moderated_by',
            field=models.ForeignKey(blank=True, help_text='Admin who moderated this review', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='moderation_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection (visible to user)', null=True),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['moderated_at'], name='bookings_re_moderat_59c4e5_idx'),
        ),
    ]
