# Generated by Django 4.2.7 on 2026-06-26 05:37

import bookings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0018_alter_equipment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingroom',
            name='floor_plan',
            field=models.ImageField(blank=True, null=True, upload_to='floor_plans/', validators=[bookings.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='meetingroom',
            name='room_photo',
            field=models.ImageField(blank=True, null=True, upload_to='room_photos/', validators=[bookings.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='resource',
            name='floor_plan',
            field=models.ImageField(blank=True, help_text='Upload a floor plan of the room', null=True, upload_to='floor_plans/', validators=[bookings.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='resource',
            name='room_photo',
            field=models.ImageField(blank=True, help_text='Upload a photo of the room', null=True, upload_to='room_photos/', validators=[bookings.models.validate_image_size]),
        ),
    ]
